name       : libexttextcat
version    : 3.4.4
release    : 1
source     :
    - http://dev-www.libreoffice.org/src/libexttextcat/libexttextcat-3.4.4.tar.xz : f24c086cf3523424228ed58b9f678cc7647688822e5407d5fbc155fbfc846293
license    : BSD-3-Clause
component  : programming
summary    : Text Categorization library for language guessing
description: |
    libexttextcat is an N-Gram-Based Text Categorization library primarily intended for language guessing.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
